# this corresponds to the default config

# MODEL:
#   WEIGHTS: bbu_logs/bbu_vits14-bs_256/eval/training_7849/teacher_checkpoint.pth

train:
  dataset_path: BBU:root=./bbu_full_dataset:split=train
  batch_size_per_gpu: 256
  saveckp_freq: 200
  seed: 17
  num_workers: 8
  OFFICIAL_EPOCH_LENGTH: 50
  centering: "centering" # or "sinkhorn_knopp"
  output_dir: 'bbu_logs/bbu_vits14-bs_256'
validation:
  dataset_path: BBU:root=./bbu_full_dataset:split=val
  batch_size_per_gpu: 512
  num_workers: 8

student:
  block_chunks: 4
  arch: vit_small
  patch_size: 14
  pretrained_weights: bbu_logs/bbu_vits14-bs_256/eval/training_7849/teacher_checkpoint.pth

crops:
  local_crops_size: 98

evaluation:
  eval_period_iterations: 250
