# this corresponds to the default config

# MODEL:
  # WEIGHTS: bbu_logs/bbu_vits14-bs_64

train:
  dataset_path: BBU:root=./bbu_full_dataset:split=train
  batch_size_per_gpu: 128
  saveckp_freq: 200
  seed: 17
  num_workers: 8
  OFFICIAL_EPOCH_LENGTH: 32 # For batch size per gpu = 64, set to be 500. 500 / (double * 8 ) = 500/16 = 32
  centering: "centering" # or "sinkhorn_knopp"
  output_dir: 'bbu_logs/bbu-vitb14-bs_pergpu_128-lr_1e-4'
validation:
  dataset_path: BBU:root=./bbu_full_dataset:split=val
  batch_size_per_gpu: 512
  num_workers: 8

student:
  block_chunks: 4
  arch: vit_base
  patch_size: 14

teacher:
  warmup_teacher_temp_epochs: 30

crops:
  local_crops_size: 98

evaluation:
  eval_period_iterations: 400

optim:
  epochs: 100
  base_lr: 0.004  # learning rate for a batch size of 1024
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 10
  min_lr: 1.0e-06