# this corresponds to the default config

# MODEL:
  # WEIGHTS: bbu_logs/bbu_vits14-bs_64
train:
  dataset_path:
    - JOINED:root=./mixed_data_root/bbu_shield_cleaned:split=train
    - JOINED:root=./mixed_data_root/bbu_grounding_wire_cleaned:split=train
    - JOINED:root=./mixed_data_root/integrated_cabinet_power_supply_cleaned:split=train
  batch_size_per_gpu: 256
  saveckp_freq: 2000
  seed: 17
  num_workers: 8
  OFFICIAL_EPOCH_LENGTH: 2500  # ignored for distributed sampler
  centering: "centering" # or "sinkhorn_knopp"
  output_dir: 'joined_logs/vitb14-total_bs_1024-lr_4e-3-epochs_30-epoch_len_2500-warmup_5-teacher_warmup_10'
  # sampler_type: DISTRIBUTED

optim:
  epochs: 30
  base_lr: 4.0e-03
  warmup_epochs: 5
  min_lr: 1.0e-06

# validation:
#   dataset_path: JOINED:root=./bbu_shield_cleaned:split=val
#   batch_size_per_gpu: 512
#   num_workers: 8
#   sampler_type: EPOCH

student:
  block_chunks: 4
  arch: vit_base
  patch_size: 14
teacher:
  warmup_teacher_temp_epochs: 10

crops:
  local_crops_size: 98

evaluation:
  eval_period_iterations: 2000

