# this corresponds to the default config
train:
  dataset_path: BBU:root=./bbu_full_dataset:split=train
  batch_size_per_gpu: 256
  saveckp_freq: 100
  seed: 17
  num_workers: 8
  OFFICIAL_EPOCH_LENGTH: 500
  centering: "centering" # or "sinkhorn_knopp"
  output_dir: 'bbu_logs/bbu_vits14-bs_256'

student:
  block_chunks: 4
  arch: vit_small
  patch_size: 14

crops:
  local_crops_size: 98

evaluation:
  eval_period_iterations: 500
